import type { WorkbenchData } from '@/components/WorkbenchShellV2';

export const MOCK_DATA: WorkbenchData = {
  userName: 'Maya',
  userInitials: 'MR',
  city: 'Chicago, IL',
  greeting: '3 new HYPEs on Sundown. Halflight FM Ep 04 hit 2,284 listens overnight. Cobalt Hour opens for you Saturday.',
  listeningNow: 1284,
  hypedToday: 432,
  showsTonight: 7,
  activeProfileTypes: ['LISTENER', 'ARTIST'],
  profileType: 'ARTIST',
  isAdmin: false,
  profilePath: '/artists/maya-reyes',
  isVerified: true,
  verificationRequested: false,
  pendingVenueRequestCount: 0,
  profileCompletion: { percent: 100, missing: [] },
  stats: [
    { label: 'HYPE THIS WEEK', value: '1,247', delta: '↑ 23% vs last wk', color: '#ff3e9a' },
    { label: 'SEEDS → SAVES',  value: '34%',   delta: '+4 pts vs last wk', color: '#ff5029' },
    { label: 'TICKETS SOLD',   value: '184',   delta: '↑ 12 today · 45% to you', color: '#22e5d4' },
    { label: 'PAYOUT PENDING', value: '$2,460', delta: '45/45/10 · releases Jun 24', color: '#ffb84a' },
  ],
  tracks: [
    { id:'t1', title:'Sundown',        artistName:'Maya Reyes',    duration:'3:24', durationSec:204, hypeCount:142, color:'#ff5029', album:'Halflight EP', mediaUrl:'' },
    { id:'t2', title:'Westline',       artistName:'Cobalt Hour',   duration:'4:11', durationSec:251, hypeCount:89,  color:'#b983ff', album:'Single',       mediaUrl:'' },
    { id:'t3', title:'Gold Teeth',     artistName:'Vela',          duration:'2:58', durationSec:178, hypeCount:67,  color:'#22e5d4', album:'Static Bloom', mediaUrl:'' },
    { id:'t4', title:'Slow Burn',      artistName:'The Lowriders', duration:'3:42', durationSec:222, hypeCount:211, color:'#ff3e9a', album:'Side Roads',   mediaUrl:'' },
    { id:'t5', title:'Cassette Heart', artistName:'Juno North',    duration:'3:09', durationSec:189, hypeCount:54,  color:'#ffb84a', album:'Single',       mediaUrl:'' },
    { id:'t6', title:'Underpass',      artistName:'Saint Hex',     duration:'4:36', durationSec:276, hypeCount:128, color:'#7fb3ff', album:'Night Architect', mediaUrl:'' },
    { id:'t7', title:'Halflight',      artistName:'Maya Reyes',    duration:'3:51', durationSec:231, hypeCount:76,  color:'#ff5029', album:'Halflight EP', mediaUrl:'' },
    { id:'t8', title:'Brass City',     artistName:'Cobalt Hour',   duration:'3:18', durationSec:198, hypeCount:33,  color:'#b983ff', album:'Single',       mediaUrl:'' },
  ],
  shows: [
    { id:'s1', name:'Maya Reyes',    venue:'Empty Bottle',     date:'Thu Jun 18', time:'9:00 PM', hype:412, sold:148, capacity:200, price:18, status:'TONIGHT' },
    { id:'s2', name:'Cobalt Hour',   venue:'Sleeping Village', date:'Sat Jun 20', time:'8:00 PM', hype:287, sold:91,  capacity:150, price:15, status:'THIS WEEK' },
    { id:'s3', name:'Vela',          venue:'Subterranean',     date:'Tue Jun 23', time:'8:00 PM', hype:156, sold:42,  capacity:180, price:12, status:'UPCOMING' },
    { id:'s4', name:'The Lowriders', venue:'Hideout',          date:'Fri Jun 26', time:'10:00 PM',hype:331, sold:201, capacity:225, price:20, status:'NEAR SOLD' },
  ],
  tickets: [
    { id:'tk1', showName:'Cobalt Hour @ Sleeping Village', date:'Sat Jun 20 · 8PM', seat:'GA',        price:15, status:'CONFIRMED', code:'iH-AX91-CB20' },
    { id:'tk2', showName:'Vela @ Subterranean',            date:'Tue Jun 23 · 8PM', seat:'GA',        price:12, status:'CONFIRMED', code:'iH-VE23-7K4M' },
    { id:'tk3', showName:'Saint Hex @ Lincoln Hall',       date:'Sat Jul 11 · 9PM', seat:'BALCONY 4', price:24, status:'WAITLIST',  code:'—' },
  ],
  activity: [
    { text:'3 new HYPEs on Sundown',                         time:'2m ago',  kind:'hype'   },
    { text:'Cobalt Hour confirmed for Sat Jun 20',           time:'14m ago', kind:'show'   },
    { text:'DJ Vex spun Sundown on Chicago Underground',     time:'1h ago',  kind:'radio'  },
    { text:'Sundown seed: 88 saves · 26% save-rate today',  time:'2h ago',  kind:'hype'   },
    { text:'Payout $2,460 · 45/45/10 · releases Jun 24',    time:'3h ago',  kind:'payout' },
  ],
  radioShows: [
    { id:'r1', name:'Chicago Underground', host:'DJ Vex',      time:'Thu 9PM',  next:'in 2h',   live:true,  listeners:412, color:'#ff3e9a', desc:'Chicago indie + post-punk. Live tonight from the Empty Bottle basement.' },
    { id:'r2', name:'After Hours',         host:'Saint Hex',   time:'Daily 11PM',next:'tonight', live:false, listeners:128, color:'#7fb3ff', desc:'Slow-burn ambient and downtempo. One hour, no talking.' },
    { id:'r3', name:'New Tape Tuesday',    host:'Juno North',  time:'Tue 7PM',  next:'next Tue',live:false, listeners:67,  color:'#ffb84a', desc:'Cassette-only releases from the Midwest underground.' },
    { id:'r4', name:'Halflight FM',        host:'Maya Reyes',  time:'Sun 10AM', next:'Sunday',  live:false, listeners:289, color:'#ff5029', desc:'Maya plays her writing-room playlist, plus one new track from the EP each week.' },
    { id:'r5', name:'Side Roads',          host:'The Lowriders',time:'Fri 8PM', next:'Friday',  live:false, listeners:184, color:'#22e5d4', desc:'Country-fried Americana with a left turn. Listener requests welcome.' },
  ],
  notifications: [],
  pageEditor: {
    profileId: 'mock-profile',
    slug: 'maya-reyes',
    type: 'ARTIST',
    name: 'Maya Reyes',
    headline: 'Halflight EP out now.',
    bio: 'Writing the next thing in a basement on Western Ave. Recommendations open.',
    aboutContent: 'Singer, songwriter, and late-night Chicago scene regular.',
    topFiveContent: '1. Westline\n2. Gold Teeth\n3. Cassette Heart\n4. Brass City\n5. Underpass',
    mediaContent: 'New live room video and photo set coming soon.',
    nowPlaying: 'Sundown — Maya Reyes',
    links: 'https://ihype.org/artists/maya-reyes',
    merchUrl: 'https://merch.example/maya',
    merchContent: 'Halflight vinyl, shirts, and limited zines.',
    tourContent: 'Midwest dates forming around June and July.',
    requestContent: 'Open to Chicago and Milwaukee support slots.',
    upcomingContent: 'Empty Bottle · Jun 18',
    previousShowHighlights: 'Sold out Hideout listening room set.',
    addressLine1: '',
    city: 'Chicago',
    stateRegion: 'IL',
    postalCode: '',
    country: 'US',
    hoursText: '',
    parkingDetails: '',
    stayRecommendations: '',
    heroImage: '',
    avatarImage: '',
    logoImage: '',
    galleryImage: '',
    featureVideoUrl: '',
    themePreset: 'midnight-neon',
    themeAccentTone: 'ember',
    themeBackdropTone: 'noir',
    fanShareEnabled: true,
    songs: [
      { hexId: 'song1', title: 'Sundown', notes: 'Lead single', freeUseEnabled: true },
      { hexId: 'song2', title: 'Halflight', notes: 'EP title track', freeUseEnabled: false },
    ],
    upcomingShows: [
      { id:'s1', name:'Maya Reyes', venue:'Empty Bottle', date:'Thu Jun 18', time:'9:00 PM', hype:412, sold:148, capacity:200, price:18, status:'TONIGHT' },
    ],
    previousShows: [
      { id:'s0', name:'Maya Reyes', venue:'Hideout', date:'Fri May 15', time:'8:00 PM', hype:201, sold:120, capacity:120, price:15, status:'THIS WEEK' },
    ],
  },
  lifeStats: { totalHype: 1247, totalEarnings: 2460, songsPlayed: 4821, eventsAttended: 12 },
};
