/**
 * FullPlayer — VENDORED FROM THE DESIGN SYSTEM. Do not edit.
 *
 * Generated by `npm run vendor:ds` from `design/handoff-console-2026-08-21/component-source`
 * (`components/shell/FullPlayer.jsx` in the design system's own tree). `npm run guard:ds`
 * fails if this file and that source have drifted apart, so a change made here
 * is reverted rather than merged: the design system is the source of truth for
 * these components, per its README ("Do not port the components by hand").
 *
 * The only edits the generator makes are the client directive, the React import,
 * the typed re-export, and px type sizes converted to rem at the design system's
 * own floor (ADHERENCE.md rule 3). Every conversion is listed in
 * `design/handoff-console-2026-08-21/VENDOR_REPORT.md`.
 */

/* eslint-disable */
// @ts-nocheck
// The body below is the design system's own JavaScript, copied verbatim.
// Type-checking it would mean editing it, which is the one thing this
// directory exists to prevent. The public surface IS checked: the typed
// re-export at the bottom carries the props interface from the design
// system's `.d.ts`, so every call site is checked as usual.

'use client';

import * as React from 'react';
import { dsFontSize } from './_ds-runtime';

/* `PlayerTrack` is declared by `./PlayerPill`, which this handoff does not ship as
   source. Vendored as an open record rather than an invented shape. */
type PlayerTrack = Record<string, any>;
export interface FullPlayerProps {
  /** Phone only. Opened by the bar's artwork, closed by the corner square. */
  open?: boolean;
  track?: PlayerTrack;
  playing?: boolean;
  /** 0–100. */
  progress?: number;
  /** 0–100. */
  volume?: number;
  hyped?: boolean;
  /** Hype spent; the 24-hour window has not reopened. */
  hypeLocked?: boolean;
  /** Wait remaining, e.g. "17h 40m". */
  hypeLabel?: string;
  faved?: boolean;
  queue?: PlayerTrack[];
  history?: PlayerTrack[];
  /** Device insets. The overlay is fixed, so it owns its own safe area. */
  safeTop?: number;
  safeBottom?: number;
  onClose?: () => void;
  onTogglePlay?: () => void;
  onPrev?: () => void;
  onNext?: () => void;
  onSeek?: (pct: number) => void;
  onVolume?: (pct: number) => void;
  onToggleHype?: () => void;
  onToggleFav?: () => void;
  onPickTrack?: (track: PlayerTrack, list: 'queue' | 'history', index: number) => void;
  onOpenArtist?: (track: PlayerTrack) => void;
  onOpenAlbum?: (track: PlayerTrack) => void;
}

const _FP = {
  base: '#34200f', surf: '#4a2b16', raised: '#4a2b16',
  ink: '#f6ecd9', ink2: '#d8c6a6', ink3: '#bda882',
  acc: '#ff5029', line: 'rgba(246,236,217,.16)', hair: 'rgba(246,236,217,.08)',
  fd: "'Instrument Serif',serif", fb: "'Work Sans',system-ui,sans-serif",
  fm: "'JetBrains Mono',monospace",
};

/**
 * The full-screen player. Phone only.
 *
 * The phone bar carries three things: artwork, the two names, transport. Every
 * other control the desktop pill has — scrub, volume, HYPE, favourite, queue,
 * history — lives here instead of being crushed into a 250px row. Tapping the
 * artwork opens this; the iHYPE square in the bottom-left corner closes it.
 *
 * That square is deliberately the same object in the same place as the shell's
 * nav trigger: on this screen it means "back", and putting it anywhere else
 * would make the way out somewhere new to look. It is a different control with
 * the same body, which is why it carries its own label.
 *
 * Everything is drawn at its final value. No CSS keyframes and no transitions
 * that depend on the document timeline advancing.
 */

function ring(size, stroke, pct, colorOn, colorOff) {
  const r = (size - stroke) / 2;
  const c = 2 * Math.PI * r;
  return React.createElement('svg', {
    width: size, height: size, viewBox: '0 0 ' + size + ' ' + size, 'aria-hidden': 'true',
    style: { position: 'absolute', inset: 0 },
  },
    React.createElement('circle', { cx: size / 2, cy: size / 2, r, fill: 'none', stroke: colorOff, strokeWidth: stroke }),
    React.createElement('circle', {
      cx: size / 2, cy: size / 2, r, fill: 'none', stroke: colorOn, strokeWidth: stroke, strokeLinecap: 'round',
      strokeDasharray: c, strokeDashoffset: c * (1 - Math.max(0, Math.min(100, pct)) / 100),
      transform: 'rotate(-90 ' + size / 2 + ' ' + size / 2 + ')',
    })
  );
}

/* Matches PlayerPill's default: the bar and this screen show the same track, so
   they must agree on how long it is. A track may carry its own `seconds`. */
function clock(pct, seconds) {
  const total = seconds || 220;
  const s = Math.round((Math.max(0, Math.min(100, pct)) / 100) * total);
  return Math.floor(s / 60) + ':' + String(s % 60).padStart(2, '0');
}

function bar({ value, onSeek, label, accent = true, height = 6 }) {
  const seek = (e) => {
    if (!onSeek) return;
    const b = e.currentTarget.getBoundingClientRect();
    onSeek(Math.max(0, Math.min(100, ((e.clientX - b.left) / b.width) * 100)));
  };
  return React.createElement('div', {
    role: 'slider', tabIndex: 0,
    'aria-label': label, 'aria-valuenow': Math.round(value), 'aria-valuemin': 0, 'aria-valuemax': 100,
    onPointerDown: (e) => { e.currentTarget.setPointerCapture(e.pointerId); seek(e); },
    onPointerMove: (e) => { if (e.buttons === 1) seek(e); },
    onKeyDown: (e) => {
      if (!onSeek) return;
      if (e.key === 'ArrowRight') onSeek(Math.min(100, value + 5));
      if (e.key === 'ArrowLeft') onSeek(Math.max(0, value - 5));
    },
    style: {
      flex: 1, height, borderRadius: 9999, background: 'rgba(246,236,217,.1)',
      cursor: onSeek ? 'pointer' : 'default', overflow: 'hidden', touchAction: 'none',
    },
  }, React.createElement('div', {
    style: {
      height: '100%', width: Math.max(0, Math.min(100, value)) + '%',
      borderRadius: 9999, background: accent ? _FP.acc : _FP.ink2,
    },
  }));
}

function FullPlayerImpl({
  open = false, track, playing = false, progress = 0, volume = 70,
  hyped = false, hypeLocked = false, hypeLabel, faved = false,
  queue = [], history = [], safeTop = 0, safeBottom = 0,
  onClose, onTogglePlay, onPrev, onNext, onSeek, onVolume,
  onToggleHype, onToggleFav, onPickTrack, onOpenArtist, onOpenAlbum,
}) {
  if (!open || !track) return null;

  const round = (glyph, label, onClick, size, tone) => React.createElement('button', {
    type: 'button', onClick, 'aria-label': label,
    style: {
      width: size, height: size, flex: '0 0 auto', padding: 0, borderRadius: 9999,
      background: 'linear-gradient(180deg,#5a3a1e,#2c1a0c)',
      border: '2px solid ' + (tone || '#8a6a2c'),
      boxShadow: 'inset 0 1px 0 rgba(255,214,160,.2), inset 0 -2px 4px rgba(0,0,0,.5)',
      color: '#f6ecd9', display: 'grid', placeItems: 'center',
      fontSize: dsFontSize(Math.round(size * 0.42)), cursor: 'pointer',
    },
  }, React.createElement('span', { 'aria-hidden': 'true' }, glyph));

  return React.createElement('div', {
    role: 'dialog', 'aria-modal': 'true', 'aria-label': 'Now playing',
    style: {
      position: 'fixed', inset: 0, zIndex: 900,
      background: 'linear-gradient(180deg,#4a2b16 0%,#34200f 45%,#1a1206 100%)',
      display: 'flex', flexDirection: 'column',
      paddingTop: safeTop, paddingBottom: safeBottom,
      fontFamily: _FP.fb, color: _FP.ink, overflow: 'hidden',
    },
  },
    React.createElement('div', {
      style: { flex: 1, minHeight: 0, overflowY: 'auto', WebkitOverflowScrolling: 'touch', padding: '18px 20px 4px' },
    },
      React.createElement('div', {
        style: { fontFamily: _FP.fm, fontSize: '0.6875rem', letterSpacing: '.2em', textTransform: 'uppercase', color: _FP.ink3, textAlign: 'center' },
      }, playing ? 'Now playing' : 'Paused'),

      /* The artwork at the size the phone can actually give it. Square, capped
         so the controls below never get pushed off a short screen. */
      React.createElement('div', {
        style: {
          /* The plate is capped against viewport HEIGHT as well as width. At a
             short height the square used to push the transport and the HYPE row
             past the bottom of a fixed, non-scrolling overlay — the same
             constraint already fixed on the seed card and the inline player. */
          width: 'min(72vw, 300px, 38vh)', aspectRatio: '1', margin: '18px auto 0',
          borderRadius: 2, background: 'linear-gradient(160deg,#ff8a52,#c9401c 60%,#7a2412)',
          boxShadow: '0 0 0 3px #c9a54e, inset 0 3px 10px rgba(0,0,0,.5), 0 18px 36px -12px rgba(0,0,0,.6)',
          display: 'grid', placeItems: 'center',
          fontFamily: _FP.fd, fontWeight: 400, fontSize: '6rem', letterSpacing: 'normal',
          color: 'rgba(255,255,255,.85)',
        },
      }, track.initial),

      React.createElement('div', { style: { textAlign: 'center', marginTop: 22 } },
        React.createElement('div', {
          style: { fontFamily: _FP.fd, fontWeight: 400, fontSize: '1.625rem', letterSpacing: 'normal', lineHeight: 1.15 },
        }, track.title),
        React.createElement('div', {
          style: { display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 7, marginTop: 7, fontSize: '0.9375rem', color: _FP.ink2 },
        },
          React.createElement('button', {
            type: 'button', onClick: () => onOpenArtist && onOpenArtist(track),
            style: {
              background: 'transparent', border: 0, padding: 0, cursor: 'pointer', font: 'inherit',
              color: _FP.ink2, textDecoration: 'underline', textDecorationColor: 'rgba(150,161,181,.4)', textUnderlineOffset: 3,
            },
          }, track.artist),
          track.album ? React.createElement('span', { 'aria-hidden': 'true', style: { color: _FP.ink3 } }, '·') : null,
          track.album ? React.createElement('button', {
            type: 'button', onClick: () => onOpenAlbum && onOpenAlbum(track),
            style: {
              background: 'transparent', border: 0, padding: 0, cursor: 'pointer', font: 'inherit',
              color: _FP.ink2, textDecoration: 'underline', textDecorationColor: 'rgba(150,161,181,.4)', textUnderlineOffset: 3,
            },
          }, track.album) : null
        )
      ),

      React.createElement('div', { style: { display: 'flex', alignItems: 'center', gap: 11, marginTop: 22 } },
        React.createElement('span', { style: { fontFamily: _FP.fm, fontSize: '0.9375rem', color: _FP.ink3, minWidth: 34 } }, clock(progress, track.seconds)),
        bar({ value: progress, onSeek, label: 'Seek' }),
        React.createElement('span', { style: { fontFamily: _FP.fm, fontSize: '0.9375rem', color: _FP.ink3, minWidth: 34, textAlign: 'right' } }, clock(100, track.seconds))
      ),

      React.createElement('div', {
        style: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 22, marginTop: 20 },
      },
        round('\u2039', 'Previous track', onPrev, 52),
        React.createElement('button', {
          type: 'button', onClick: onTogglePlay,
          'aria-label': playing ? 'Pause' : 'Play',
          style: {
            position: 'relative', width: 78, height: 78, flex: '0 0 auto', padding: 0,
            borderRadius: 9999, background: 'radial-gradient(circle at 35% 30%,#ff8a5c,' + _FP.acc + ' 55%,#c9401c 100%)',
            border: '2px solid #c9a54e', color: '#fff8ef',
            display: 'grid', placeItems: 'center', cursor: 'pointer',
            fontSize: '1.5rem', paddingLeft: playing ? 0 : 5,
            boxShadow: '0 10px 20px -6px rgba(0,0,0,.5)',
          },
        },
          ring(78, 3, progress, 'rgba(255,255,255,.9)', 'rgba(255,255,255,.22)'),
          React.createElement('span', { 'aria-hidden': 'true' }, playing ? '\u275a\u275a' : '\u25b6')
        ),
        round('\u203a', 'Next track', onNext, 52)
      ),

      React.createElement('div', {
        style: { display: 'flex', alignItems: 'center', gap: 12, marginTop: 22 },
      },
        React.createElement('button', {
          type: 'button', onClick: hypeLocked ? undefined : onToggleHype, disabled: hypeLocked,
          'aria-label': hypeLocked
            ? 'Already hyped ' + track.artist + '. ' + (hypeLabel || '') + ' until you can hype again'
            : 'Hype ' + track.artist,
          'aria-pressed': hyped,
          style: {
            flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
            height: 52, borderRadius: 9999, cursor: hypeLocked ? 'default' : 'pointer',
            background: hypeLocked ? 'rgba(255,80,41,.08)' : (hyped ? _FP.acc : 'rgba(255,80,41,.14)'),
            border: '1px solid ' + (hypeLocked ? 'rgba(255,80,41,.28)' : (hyped ? _FP.acc : 'rgba(255,80,41,.45)')),
            color: hypeLocked ? 'rgba(255,80,41,.6)' : (hyped ? '#1c1408' : _FP.acc),
          },
        },
          React.createElement('span', {
            style: { fontFamily: _FP.fd, fontWeight: 400, fontSize: '1rem', letterSpacing: '.06em' },
          }, 'HYPE'),
          hypeLocked && hypeLabel ? React.createElement('span', {
            style: { fontFamily: _FP.fm, fontWeight: 500, fontSize: '0.9375rem', opacity: .85 },
          }, hypeLabel) : null
        ),
        round(faved ? '\u2665' : '\u2661', faved ? 'Remove from your library' : 'Save to your library', onToggleFav, 52, faved ? _FP.acc : undefined)
      ),

      React.createElement('div', { style: { display: 'flex', alignItems: 'center', gap: 11, marginTop: 18 } },
        React.createElement('span', { 'aria-hidden': 'true', style: { fontFamily: _FP.fm, fontSize: '0.9375rem', color: _FP.ink3 } }, '\u266b'),
        bar({ value: volume, onSeek: onVolume, label: 'Volume', accent: false, height: 4 }),
        React.createElement('span', { style: { fontFamily: _FP.fm, fontSize: '0.9375rem', color: _FP.ink3, minWidth: 30, textAlign: 'right' } }, Math.round(volume) + '%')
      ),

      queue.length ? React.createElement('div', { style: { marginTop: 26 } },
        React.createElement('div', {
          style: { fontFamily: _FP.fm, fontSize: '0.6875rem', letterSpacing: '.18em', textTransform: 'uppercase', color: _FP.ink3, marginBottom: 8 },
        }, 'Up next'),
        queue.map((t, i) => React.createElement('button', {
          key: 'q' + i, type: 'button', onClick: () => onPickTrack && onPickTrack(t, 'queue', i),
          style: {
            display: 'flex', width: '100%', alignItems: 'center', gap: 12, padding: '11px 0',
            background: 'transparent', border: 0, borderTop: i ? '1px solid ' + _FP.hair : 0,
            textAlign: 'left', cursor: 'pointer',
          },
        },
          React.createElement('span', { style: { fontFamily: _FP.fm, fontSize: '0.9375rem', color: _FP.ink3, width: 20, flex: '0 0 auto' } }, String(i + 1).padStart(2, '0')),
          React.createElement('span', { style: { flex: 1, minWidth: 0, fontSize: '0.9375rem', color: _FP.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' } }, t.title),
          React.createElement('span', { style: { fontSize: '0.9375rem', color: _FP.ink2, flex: '0 0 auto' } }, t.artist)
        ))
      ) : null,

      history.length ? React.createElement('div', { style: { marginTop: 22, borderTop: '1px solid ' + _FP.line, paddingTop: 14 } },
        React.createElement('div', {
          style: { fontFamily: _FP.fm, fontSize: '0.6875rem', letterSpacing: '.18em', textTransform: 'uppercase', color: _FP.ink3, marginBottom: 8 },
        }, 'Played'),
        history.map((t, i) => React.createElement('button', {
          key: 'h' + i, type: 'button', onClick: () => onPickTrack && onPickTrack(t, 'history', i),
          style: {
            display: 'flex', width: '100%', alignItems: 'center', gap: 12, padding: '10px 0',
            background: 'transparent', border: 0, textAlign: 'left', cursor: 'pointer', opacity: .55,
          },
        },
          React.createElement('span', { style: { fontFamily: _FP.fm, fontSize: '0.9375rem', color: _FP.ink3, width: 20, flex: '0 0 auto' } }, '\u00b7'),
          React.createElement('span', { style: { flex: 1, minWidth: 0, fontSize: '0.9375rem', color: _FP.ink2, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' } }, t.title),
          React.createElement('span', { style: { fontSize: '0.9375rem', color: _FP.ink3, flex: '0 0 auto' } }, t.artist)
        ))
      ) : null,

      React.createElement('div', { style: { height: 8 } })
    ),

    /* The way out, in the corner the way out always lives in. Same square, same
       place as the shell's trigger — on this screen it means back.

       In the column's normal flow, NOT absolutely positioned over it: floating
       above a scrolling column meant whatever happened to sit in the bottom-left
       corner at rest — the HYPE button — was painted over by it. Bottom padding
       on the scroller cannot fix that; it lengthens the scroll without moving
       an earlier child. Occupying real space can't be slid under. */
    React.createElement('div', {
      style: {
        flex: 'none', display: 'flex', alignItems: 'center', gap: 13,
        padding: '10px 20px 18px',
      },
    },
      React.createElement('button', {
        type: 'button', onClick: onClose, 'aria-label': 'Back to iHYPE',
        style: {
          width: 62, height: 62, flex: '0 0 auto', padding: 0,
          borderRadius: 21, background: _FP.acc, border: 0, color: '#1c1408',
          display: 'grid', placeItems: 'center', cursor: 'pointer',
          boxShadow: '0 8px 18px -6px rgba(0,0,0,.45)',
        },
      }, React.createElement('span', {
        style: { display: 'flex', alignItems: 'center', fontFamily: _FP.fd, fontWeight: 400, fontSize: '0.9375rem', letterSpacing: '.01em', lineHeight: 1 },
      },
        'iH',
        React.createElement('svg', {
          'aria-hidden': 'true', viewBox: '148 92 200 328', width: 11, height: 18,
          style: { display: 'block', margin: '0 .06em' },
        }, React.createElement('path', { d: 'M280 96L152 288h96l-16 128 144-192h-96l16-128z', fill: 'currentColor' })),
        'PE'
      )),
      React.createElement('span', {
        style: { fontFamily: _FP.fm, fontSize: '0.6875rem', letterSpacing: '.18em', textTransform: 'uppercase', color: _FP.ink3 },
      }, 'Back')
    )
  );
}

export const FullPlayer: (props: FullPlayerProps) => React.JSX.Element | null = FullPlayerImpl;
