/**
 * HypeButton — VENDORED FROM THE DESIGN SYSTEM. Do not edit.
 *
 * Generated by `npm run vendor:ds` from `design/handoff-console-2026-08-21/component-source`
 * (`components/core/HypeButton.jsx` in the design system's own tree). `npm run guard:ds`
 * fails if this file and that source have drifted apart, so a change made here
 * is reverted rather than merged: the design system is the source of truth for
 * these components, per its README ("Do not port the components by hand").
 *
 * The only edits the generator makes are the client directive, the React import,
 * the typed re-export, and px type sizes converted to rem at the design system's
 * own floor (ADHERENCE.md rule 3). Every conversion is listed in
 * `design/handoff-console-2026-08-21/VENDOR_REPORT.md`.
 *
 * READ BEFORE MOUNTING:
 * Reads `active` as `#ff5029` copy, which is 2.48:1 on the cream board and
 * fails AA — the design system's own rule 2 ("--accent is a fill, never
 * text"). It is legible on walnut, where the component was drawn. Pass
 * `roleColor` with an accent-as-copy value on any board surface.
 */

/* eslint-disable */
// @ts-nocheck
// The body below is the design system's own JavaScript, copied verbatim.
// Type-checking it would mean editing it, which is the one thing this
// directory exists to prevent. The public surface IS checked: the typed
// re-export at the bottom carries the props interface from the design
// system's `.d.ts`, so every call site is checked as usual.

'use client';

import * as React from 'react';
import { dsFontSize } from './_ds-runtime';

/**
 * iHYPE HypeButton component.
 * The platform's namesake mechanic — a flame toggle with a live count, scale-pop + expanding-ring
 * animation on activation. Used anywhere a fan hypes an artist, track, or show (Discover, Show Detail,
 * Track Detail, Profile Page). Owns only the tap animation; the caller owns count/active state
 * (and any hype-budget limit — pass `disabled` + `disabledReason` when the fan is out of hypes).
 */
export interface HypeButtonProps {
  /** Whether this fan has already hyped this item. */
  active?: boolean;
  /** Current hype count, already formatted (e.g. "4,821"). */
  count?: string | number;
  onToggle?: (e: React.MouseEvent) => void;
  size?: 'sm' | 'md' | 'lg';
  /** True when the fan is out of hypes this week — dims the button and disables the tap. */
  disabled?: boolean;
  /** Tooltip shown when disabled, e.g. "0 hypes left — resets Monday". */
  disabledReason?: string;
  /** Override the flame/active color (defaults to brand accent #ff5029). Use a role color for a role-scoped feed. */
  roleColor?: string;
  /** Optional momentum readout shown after the count, e.g. "▲ 340/hr" — the demand-velocity signal that sets HYPE apart from a plain like count. */
  trend?: string;
  /** Layout constraints from the caller (e.g. `flex:1` in a two-button row).
   *  The component owns its padding, radius and colour — this is for the box it
   *  occupies, nothing else. */
  style?: React.CSSProperties;
}

// iHYPE HypeButton — the platform's namesake mechanic: a tap-to-hype flame with live count.
// Self-contained: only needs React. Injects its own @keyframes once per page.
if (typeof document !== 'undefined' && !document.getElementById('_hb_kf')) {
  const s = document.createElement('style');
  s.id = '_hb_kf';
  s.textContent = '@keyframes hbPop{0%{transform:scale(1)}35%{transform:scale(1.35)}60%{transform:scale(.92)}100%{transform:scale(1)}}@keyframes hbRing{0%{opacity:.55;transform:scale(.6)}100%{opacity:0;transform:scale(2.1)}}@media(prefers-reduced-motion:reduce){[data-hb-anim]{animation:none!important}}';
  document.head.appendChild(s);
}

const SIZES = { sm: { icon: 13, pad: '5px 10px', font: 11 }, md: { icon: 16, pad: '7px 14px', font: 13 }, lg: { icon: 20, pad: '10px 18px', font: 15 } };

function Flame({ size, active }) {
  return React.createElement('svg', { width: size, height: size, viewBox: '0 0 24 24', fill: active ? 'currentColor' : 'none', stroke: 'currentColor', strokeWidth: active ? 0 : 1.8, strokeLinecap: 'round', strokeLinejoin: 'round' },
    React.createElement('path', { d: 'M12 2c1 3-2 4-2 7a4 4 0 0 0 8 0c0-1-.5-2-1-2.5.5 2-1 3-2 3 1-3-1-4-1-6-1 1-3 2-3 5a3 3 0 0 0 3 3c-3 0-6-2-6-6 0-2 1-3.5 4-3.5z' })
  );
}

/**
 * HypeButton — pill-shaped flame toggle with animated count.
 * Pass `active` + `count` + `onToggle`; the component owns only the tap animation, not the count logic.
 */
function HypeButtonImpl({ active, count, onToggle, size = 'md', disabled, disabledReason, roleColor, trend, style }) {
  const [popping, setPopping] = React.useState(false);
  const S = SIZES[size] || SIZES.md;
  const color = roleColor || '#ff5029';
  const handleClick = (e) => {
    if (disabled) return;
    setPopping(true);
    setTimeout(() => setPopping(false), 420);
    onToggle && onToggle(e);
  };
  return React.createElement('button', {
    onClick: handleClick,
    disabled,
    /* The count and the trend are the only text, so without this the control
       announces as "1,204 ▲ 340/hr" and never says what tapping it does. */
    'aria-label': (active ? 'Hyped' : 'Hype') + (count != null ? ' — ' + count : ''),
    'aria-pressed': active ? 'true' : 'false',
    title: disabled ? disabledReason : undefined,
    style: {
      position: 'relative', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 6,
      padding: S.pad, borderRadius: 999, cursor: disabled ? 'default' : 'pointer',
      fontFamily: "'JetBrains Mono', monospace", fontSize: dsFontSize(S.font), lineHeight: 1,
      /* Console tokens, not raw hex: the inactive state used pre-console navy
         ink (#eef1f6) and a dark border built for a light surface, so on walnut
         the button rendered as floating text with no visible edge. */
      border: '1px solid ' + (active ? color + '4d' : 'var(--brass-deep, #8a6a2c)'),
      background: active ? color + '1f' : 'transparent',
      color: disabled ? 'var(--ink-on-walnut-3, #bda882)' : active ? color : 'var(--ink-on-walnut, #f6ecd9)',
      opacity: disabled ? 0.55 : 1,
      transition: 'background 150ms ease, border-color 150ms ease, color 150ms ease',
      ...style,
    },
  },
    popping && React.createElement('span', {
      'data-hb-anim': true,
      style: { position: 'absolute', inset: -4, borderRadius: 999, border: `2px solid ${color}`, animation: 'hbRing 420ms ease-out both', pointerEvents: 'none' },
    }),
    React.createElement('span', { 'data-hb-anim': true, style: { display: 'inline-flex', animation: popping ? 'hbPop 420ms cubic-bezier(.34,1.56,.64,1) both' : 'none' } },
      React.createElement(Flame, { size: S.icon, active })
    ),
    React.createElement('span', null, count),
    trend && React.createElement('span', { style: { fontSize: dsFontSize(S.font - 3), opacity: 0.75, marginLeft: 1 } }, trend)
  );
}

export const HypeButton: (props: HypeButtonProps) => React.JSX.Element = HypeButtonImpl;
