/**
 * RotaryNav — VENDORED FROM THE DESIGN SYSTEM. Do not edit.
 *
 * Generated by `npm run vendor:ds` from `design/handoff-console-2026-08-21/component-source`
 * (`components/shell/RotaryNav.jsx` in the design system's own tree). `npm run guard:ds`
 * fails if this file and that source have drifted apart, so a change made here
 * is reverted rather than merged: the design system is the source of truth for
 * these components, per its README ("Do not port the components by hand").
 *
 * The only edits the generator makes are the client directive, the React import,
 * the typed re-export, and px type sizes converted to rem at the design system's
 * own floor (ADHERENCE.md rule 3). Every conversion is listed in
 * `design/handoff-console-2026-08-21/VENDOR_REPORT.md`.
 *
 * READ BEFORE MOUNTING:
 * Not adoptable as-is. Its cap readout is 8.5px, which the design system's
 * own 15px content floor forbids (ADHERENCE.md rule 3 names "a dial readout"
 * as content) — and at 15px the word MUSIC does not fit the 40px cap of a
 * 74px knob. That needs a design decision upstream, not a workaround here.
 * Note also that this handoff disagrees with itself about the nav model:
 * README.md replaces the arc nav with this knob, while ADHERENCE.md rule 6
 * still describes the logo trigger and arc as the shell's only chrome.
 */

/* eslint-disable */
// @ts-nocheck
// The body below is the design system's own JavaScript, copied verbatim.
// Type-checking it would mean editing it, which is the one thing this
// directory exists to prevent. The public surface IS checked: the typed
// re-export at the bottom carries the props interface from the design
// system's `.d.ts`, so every call site is checked as usual.

'use client';

import * as React from 'react';
import { dsFontSize } from './_ds-runtime';

export interface RotaryNavModule { id: string; label: string }
export interface RotaryNavProps {
  /** In arc order, left to right across the switch's sweep. Map · Music · Me. */
  modules: RotaryNavModule[];
  activeModule?: string;
  onNavigate?: (module: RotaryNavModule) => void;
  /** Same figure the shell sizes the joystick and the player anchor from. */
  size?: number;
}

const _RN = { fm: "'JetBrains Mono',monospace" };

/**
 * The left-hand module switch — a detented rotary knob, not a menu. Map ·
 * Music · Me are the whole of the app's top level.
 *
 * Physically it is the same brass rotary body as `JoystickTransport`: knurled
 * bezel, dark inset well, brass cap. The cap reads out the current module by
 * NAME, not initial — Map, Music and Me all start with M.
 *
 * One 44px+ target, three ways in: tap steps to the next detent, drag rotates
 * and snaps to the nearest, arrow keys step. Nothing is placed outside the
 * knob's own box, so the root bounds every hit target it owns and no host has
 * to reserve an overhang.
 */
const SWEEP = 84; // degrees the pointer sweeps, clockwise from straight down

function RotaryNavImpl({ modules = [], activeModule, onNavigate, size = 74 }) {
  const idx = Math.max(0, modules.findIndex((m) => m.id === activeModule));
  const n = modules.length || 1;
  /* Positive is clockwise from straight down; modules are declared
     left-to-right, so index 0 sits at +SWEEP/2. */
  const angleFor = (i) => SWEEP / 2 - (n > 1 ? (SWEEP * i) / (n - 1) : 0);
  const [drag, setDrag] = React.useState(null);
  const rootRef = React.useRef(null);
  const moved = React.useRef(false);

  const pick = (i) => {
    const m = modules[((i % n) + n) % n];
    if (m && m.id !== activeModule) onNavigate && onNavigate(m);
  };

  const angleFromEvent = (e) => {
    const r = rootRef.current.getBoundingClientRect();
    const dx = e.clientX - (r.left + r.width / 2);
    const dy = e.clientY - (r.top + r.height / 2);
    return Math.atan2(-dx, dy) * (180 / Math.PI); // same convention as the pointer
  };
  const nearestIdx = (angle) => {
    let best = 0, bestD = Infinity;
    modules.forEach((_, i) => {
      const d = Math.abs(((angleFor(i) - angle + 540) % 360) - 180);
      if (d < bestD) { bestD = d; best = i; }
    });
    return best;
  };

  const pointerAngle = drag ? drag.angle : angleFor(idx);
  const active = modules[idx] || {};

  const ring = (inset, from, step) => React.createElement('span', {
    'aria-hidden': 'true',
    style: {
      position: 'absolute', inset, borderRadius: '9999px', opacity: 0.55,
      background: 'repeating-conic-gradient(from ' + from + 'deg,' +
        'rgba(255,244,214,.5) 0deg ' + step + 'deg,' +
        'rgba(60,42,14,.5) ' + step + 'deg ' + step * 2 + 'deg)',
    },
  });

  return React.createElement('div', {
    ref: rootRef,
    style: { position: 'relative', width: size, height: size, flex: '0 0 auto' },
  },
    React.createElement('button', {
      type: 'button',
      'aria-label': 'Module: ' + (active.label || '') + '. Tap for the next, or drag to choose.',
      onPointerDown: (e) => { e.currentTarget.setPointerCapture(e.pointerId); moved.current = false; setDrag({ angle: angleFromEvent(e) }); },
      onPointerMove: (e) => { if (!drag) return; moved.current = true; setDrag({ angle: angleFromEvent(e) }); },
      onPointerUp: () => { if (!drag) return; pick(moved.current ? nearestIdx(drag.angle) : idx + 1); setDrag(null); },
      onPointerCancel: () => setDrag(null),
      onKeyDown: (e) => {
        if (e.key === 'ArrowRight' || e.key === 'ArrowDown') { e.preventDefault(); pick(idx + 1); }
        if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') { e.preventDefault(); pick(idx - 1); }
      },
      style: {
        position: 'absolute', inset: 0, width: '100%', height: '100%', padding: 0,
        borderRadius: '9999px', cursor: 'grab', touchAction: 'none',
        border: '2px solid var(--brass-deep)',
        background: 'radial-gradient(circle at 36% 28%, var(--brass) 0%, #7a5a22 62%, #4a3512 100%)',
        boxShadow: '0 6px 14px -5px rgba(0,0,0,.7), inset 0 1px 0 rgba(255,244,214,.5)',
      },
    },
      ring(1, 0, 2.2),
      React.createElement('span', {
        'aria-hidden': 'true',
        style: {
          position: 'absolute', inset: 6, borderRadius: '9999px',
          background: 'radial-gradient(circle at 40% 32%, var(--walnut-2), #1c1206)',
          border: '1px solid rgba(255,214,160,.2)',
        },
      }),
      React.createElement('span', {
        'aria-hidden': 'true',
        style: {
          position: 'absolute', inset: 6, borderRadius: '9999px',
          transform: 'rotate(' + pointerAngle + 'deg)',
          transition: drag ? 'none' : 'transform 280ms cubic-bezier(.28,1.5,.35,1)',
        },
      },
        React.createElement('span', {
          style: {
            position: 'absolute', left: '50%', bottom: 4, width: 2.5, height: size * 0.17,
            marginLeft: -1.25, borderRadius: 2, background: 'var(--lamp)',
            boxShadow: '0 0 7px rgba(255,184,74,.9)',
          },
        })
      ),
      React.createElement('span', {
        style: {
          position: 'absolute', left: '50%', top: '50%',
          width: size * 0.54, height: size * 0.54, margin: '0 0 0 0',
          transform: 'translate(-50%,-50%)', borderRadius: '9999px',
          display: 'grid', placeItems: 'center',
          border: '1.5px solid var(--brass-deep)',
          background: 'radial-gradient(circle at 36% 30%, #e0c076, var(--brass) 52%, var(--brass-deep))',
          boxShadow: '0 4px 9px -3px rgba(0,0,0,.65), inset 0 1px 0 rgba(255,248,224,.6)',
          fontFamily: _RN.fm, fontWeight: 700, fontSize: dsFontSize(Math.max(8, size * 0.115)),
          letterSpacing: '.06em', color: 'var(--walnut-3)', userSelect: 'none',
        },
      }, (active.label || '').toUpperCase())
    )
  );
}

export const RotaryNav: (props: RotaryNavProps) => React.JSX.Element = RotaryNavImpl;
