/**
 * TunerDial — VENDORED FROM THE DESIGN SYSTEM. Do not edit.
 *
 * Generated by `npm run vendor:ds` from `design/handoff-console-2026-08-21/component-source`
 * (`components/shell/TunerDial.jsx` in the design system's own tree). `npm run guard:ds`
 * fails if this file and that source have drifted apart, so a change made here
 * is reverted rather than merged: the design system is the source of truth for
 * these components, per its README ("Do not port the components by hand").
 *
 * The only edits the generator makes are the client directive, the React import,
 * the typed re-export, and px type sizes converted to rem at the design system's
 * own floor (ADHERENCE.md rule 3). Every conversion is listed in
 * `design/handoff-console-2026-08-21/VENDOR_REPORT.md`.
 */

/* eslint-disable */
// @ts-nocheck
// The body below is the design system's own JavaScript, copied verbatim.
// Type-checking it would mean editing it, which is the one thing this
// directory exists to prevent. The public surface IS checked: the typed
// re-export at the bottom carries the props interface from the design
// system's `.d.ts`, so every call site is checked as usual.

'use client';

import * as React from 'react';

export interface TunerStation { id: string; label: string }
export interface TunerDialProps {
  /** Stations in scale order — wraps in both directions. */
  stations: TunerStation[];
  active: string;
  onChange?: (id: string) => void;
  style?: React.CSSProperties;
}
/**
 * The console's signature control — replaces a horizontal tab strip.
 * Drag or wheel the dial, or press either brass key. role="tablist" of
 * role="tab", not role="slider": announces a destination name, not a number.
 */

const _TD = { fs: "'Instrument Serif',serif", fm: "'JetBrains Mono',monospace" };

/**
 * The tuner dial — replaces every horizontal tab strip in the console
 * direction. A strip divides one row by the number of tabs, so each tab added
 * shrinks every label; the dial spends the whole row on ONE destination at a
 * large size and does not shrink when a section is added.
 *
 * Semantics: role="tablist" of role="tab" buttons with roving tabindex, NOT
 * role="slider" — a slider announces a number where a member needs a
 * destination name. Drag or wheel to tune; the dial itself is focusable and
 * takes Left/Right, so the step chevrons are affordances inside the lit face
 * rather than separate hardware flanking it (which ate a third of the row).
 *
 * The scale is two repeating-linear-gradients whose background-position is
 * driven by drag distance — no cloned strip, no seam, wraps both ways for
 * free. PITCH (46px) is the major-tick spacing AND the drag distance per
 * station; the two must move together or the needle drifts off the scale.
 */
const PITCH = 46;

function TunerDialImpl({ stations = [], active, onChange, style }) {
  /* `active` naming no station is a wiring bug, not a state to render: falling
     back to index 0 shows a confident, wrong destination — which is exactly how
     a prop collision on `stations` once had a dock dial reading out the page's
     own tab set. Say so, then fall back, so the dial is never silently lying. */
  const found = stations.findIndex((s) => s.id === active);
  if (found < 0 && stations.length && active !== undefined) {
    console.warn('TunerDial: active "' + active + '" is not one of [' + stations.map((s) => s.id).join(', ') + '] — showing the first station.');
  }
  const idx = Math.max(0, found);
  const [drag, setDrag] = React.useState(null);

  const go = (i) => {
    const n = ((i % stations.length) + stations.length) % stations.length;
    onChange && stations[n] && onChange(stations[n].id);
  };

  /* The scale scrolls with the WHOLE drag, not the remainder within one detent:
     modulo made the ticks snap back to centre every 46px, which read as the
     scale refusing to travel. */
  const bandOffset = (drag ? drag.dx : 0) + 'px';

  const chev = (dir, label) => React.createElement('button', {
    key: dir, type: 'button', 'aria-label': label, tabIndex: -1,
    onPointerDown: (e) => e.stopPropagation(),
    onClick: (e) => { e.stopPropagation(); go(idx + dir); },
    style: {
      position: 'absolute', top: 0, bottom: 0, [dir < 0 ? 'left' : 'right']: 0,
      width: 26, border: 0, background: 'none', cursor: 'pointer', zIndex: 2,
      color: 'rgba(92,62,20,.6)', fontFamily: _TD.fm, fontSize: '0.9375rem', lineHeight: 1,
      display: 'grid', placeItems: 'center', padding: 0,
    },
  }, dir < 0 ? '\u2039' : '\u203a');

  return React.createElement('div', {
    className: 'tuner-dial', role: 'tablist', 'aria-label': 'Sections',
    tabIndex: 0,
    onPointerDown: (e) => { e.currentTarget.setPointerCapture(e.pointerId); setDrag({ startX: e.clientX, startIdx: idx, dx: 0 }); },
    /* A real dial tunes THROUGH stations: the station changes as the needle
       passes each detent, so one long drag can cross the whole scale. Reporting
       only at release made the dial a stepper that moved once per gesture. */
    onPointerMove: (e) => {
      if (!drag) return;
      const dx = e.clientX - drag.startX;
      setDrag((d) => ({ ...d, dx }));
      const steps = -Math.round(dx / PITCH);
      const target = ((drag.startIdx + steps) % stations.length + stations.length) % stations.length;
      if (stations[target] && stations[target].id !== active) onChange && onChange(stations[target].id);
    },
    onPointerUp: () => setDrag(null),
    onPointerCancel: () => setDrag(null),
    onWheel: (e) => { e.preventDefault(); go(idx + (e.deltaY > 0 || e.deltaX > 0 ? 1 : -1)); },
    onKeyDown: (e) => {
      if (e.key === 'ArrowRight') { e.preventDefault(); go(idx + 1); }
      if (e.key === 'ArrowLeft') { e.preventDefault(); go(idx - 1); }
    },
    style: { display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: 2, ...style },
  },
    chev(-1, 'Previous station'),
    chev(1, 'Next station'),
    /* Three stations on the face, not one: the current at full size with its
       neighbours small at either shoulder. A tuner you cannot see past gives no
       sense of which way to turn, and the shoulders slide with the drag so the
       gesture reads as continuous travel along a scale rather than a stepper. */
    React.createElement('div', {
      style: { position: 'relative', height: 30, overflow: 'hidden' },
    },
      React.createElement('div', {
        style: {
          position: 'absolute', inset: 0,
          transform: 'translateX(' + (drag ? Math.max(-30, Math.min(30, drag.dx * 0.42)) : 0) + 'px)',
          transition: drag ? 'none' : 'transform 200ms cubic-bezier(.2,.9,.3,1)',
        },
      },
        [-1, 0, 1].map((off) => {
          const i = ((idx + off) % stations.length + stations.length) % stations.length;
          const s = stations[i];
          if (!s || (off !== 0 && stations.length < 2)) return null;
          const mid = off === 0;
          return React.createElement('button', {
            key: 'st' + off, type: 'button', role: 'tab', 'aria-selected': mid,
            tabIndex: -1,
            onPointerDown: mid ? undefined : (e) => e.stopPropagation(),
            onClick: (e) => { e.stopPropagation(); go(i); },
            style: mid ? {
              /* Inset on BOTH sides, so the longest label ellipsises inside the
                 dial rather than running over the shoulders. */
              position: 'absolute', left: '22%', right: '22%', top: 0,
              width: 'auto', border: 0, background: 'none', padding: 0, cursor: 'inherit',
              fontFamily: _TD.fs, fontSize: '1.5rem', lineHeight: 1.12,
              letterSpacing: '.005em', textAlign: 'center', color: 'var(--ink-1)',
              whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
            } : {
              position: 'absolute', top: 7, [off < 0 ? 'left' : 'right']: 24,
              maxWidth: '20%', border: 0, background: 'none', padding: 0, cursor: 'pointer',
              fontFamily: _TD.fm, fontSize: '0.9375rem', fontWeight: 700, letterSpacing: '.1em',
              textTransform: 'uppercase', color: 'rgba(92,62,20,.5)',
              whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
            },
          }, s.label);
        })
      )
    ),
    React.createElement('div', { className: 'tuner-scale', 'aria-hidden': 'true' },
      React.createElement('div', {
        className: 'tuner-ticks',
        style: { backgroundPositionX: bandOffset + ',' + bandOffset },
      }),
      React.createElement('div', { className: 'tuner-needle' })
    )
  );
}

export const TunerDial: (props: TunerDialProps) => React.JSX.Element = TunerDialImpl;
