ALTER TABLE "Profile" DROP COLUMN IF EXISTS "featureVideoUrl";
ALTER TABLE "Show" DROP COLUMN IF EXISTS "streamProvider";
ALTER TABLE "Show" DROP COLUMN IF EXISTS "streamPlaybackId";
ALTER TABLE "Show" DROP COLUMN IF EXISTS "streamKeyMasked";
