ALTER TABLE "AdSubmission" ADD COLUMN IF NOT EXISTS "clicks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AdSubmission" ADD COLUMN IF NOT EXISTS "budgetCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AdSubmission" ADD COLUMN IF NOT EXISTS "spentCents" INTEGER NOT NULL DEFAULT 0;
